gText_Birch_Welcome::
	.string "Hello there!\p"
	.string "Thank you for taking the time to\n"
	.string "view this introductory video!\p"
	.string "My name is Oak, Kanto's resident\n"
	.string "Pokémon Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "As you know, this world is filled\n" 
	.string "with Pokémon, amazing creatures\l"
	.string "we have the honor of calling our\l"
	.string "friends, pets, helpers, battling\l"
	.string "partners, and most of all, friends.\p"
	.string "As of today, you are officially\n"
	.string "a Pokémon Trainer.\p"
	.string "I'm sure you've waited a long time\n"
	.string "for this day!\p"
	.string "At my lab in Pallet Town, you will\n"
	.string "recieve a Pokémon of your choosing,\l"
	.string "as well as access to the Trainer's\l"
	.string "Edition of the PokéDex app on your\l"
	.string "RotoGear.\p"
	.string "The world will be your Cloyster once\n"
	.string "you recieve your Pokémon.\p"
	.string "You'll catch Pokémon, take on the\n"
	.string "Gym Challenge, and travel the entire\l"
	.string "Indigo Region!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Please select a character.$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Your very own Pokémon journey\n"
	.string "awaits.\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "$"
